### ISSUE TITLE
Database setup causes "ERROR 1045 (28000)"

### ISSUE THREAD

**Issue by gakindler** [nesp-tsr3-1/tsx#30]
During initializing the database as per the docs on 'Installation on Linux/macOS', I'm getting an [access denied error](https://dev.mysql.com/doc/refman/8.0/en/error-access-denied.html).

```
(env) user@pop-os:~/*/tsx$ sudo setup/setup-database.sh
[sudo] password for user:
(env) user@pop-os:~/*/tsx$ mysql tsx < sample-data/seed.sql
ERROR 1045 (28000): Access denied for user 'user'@'localhost' (using password: NO)
```

OS = "Pop!_OS 21.10"
ID_LIKE="ubuntu debian"

**Comment by ammojamo** [comment]
Can you please try putting `sudo` in front of that command, i.e:

`sudo mysql tsx < sample-data/seed.sql`

If that works, I will update the documentation.

**Comment by gakindler** [comment]
Works! Thank you!
